2. What is the use of a finally block in Python exception handling
mechanism?
Answer:
Cleanup activities like releasing external resources, network connections
or database connections etc. is done in the finally block since it gets
called irrespective of whether an exception occurred or not
