3.How does nested exception handling work in Python?
Answer:
If an exception is raised in the nested try block, the nested except block
is used to handle it. If it does not then the outer except blocks are used to
handle the exception.
